# Generated by Django 3.2.3 on 2021-05-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=50)),
                ('merek', models.CharField(max_length=50)),
                ('satuan', models.IntegerField(null=True)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
