# Generated by Django 3.2.3 on 2021-05-30 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gedung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gedung', models.CharField(max_length=10)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ruang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruang', models.CharField(max_length=3)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='barang',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='barang',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='barang',
            name='gedung_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.gedung'),
        ),
        migrations.AddField(
            model_name='barang',
            name='ruang_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.ruang'),
        ),
    ]
