# Generated by Django 3.2.3 on 2021-05-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0002_auto_20210530_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='satuan',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='barang',
            name='total_price',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
